// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "shairport_lcm_t.h"

static int __shairport_lcm_t_hash_computed;
static uint64_t __shairport_lcm_t_hash;

uint64_t __shairport_lcm_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __shairport_lcm_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__shairport_lcm_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xbcf266f30c19dbf7LL
         + __string_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __shairport_lcm_t_get_hash(void)
{
    if (!__shairport_lcm_t_hash_computed) {
        __shairport_lcm_t_hash = (int64_t)__shairport_lcm_t_hash_recursive(NULL);
        __shairport_lcm_t_hash_computed = 1;
    }

    return __shairport_lcm_t_hash;
}

int __shairport_lcm_t_encode_array(void *buf, int offset, int maxlen, const shairport_lcm_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].message), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].value), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int shairport_lcm_t_encode(void *buf, int offset, int maxlen, const shairport_lcm_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __shairport_lcm_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __shairport_lcm_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __shairport_lcm_t_encoded_array_size(const shairport_lcm_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __string_encoded_array_size(&(p[element].message), 1);

        size += __int32_t_encoded_array_size(&(p[element].value), 1);

    }
    return size;
}

int shairport_lcm_t_encoded_size(const shairport_lcm_t *p)
{
    return 8 + __shairport_lcm_t_encoded_array_size(p, 1);
}

int __shairport_lcm_t_decode_array(const void *buf, int offset, int maxlen, shairport_lcm_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].message), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].value), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __shairport_lcm_t_decode_array_cleanup(shairport_lcm_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __string_decode_array_cleanup(&(p[element].message), 1);

        __int32_t_decode_array_cleanup(&(p[element].value), 1);

    }
    return 0;
}

int shairport_lcm_t_decode(const void *buf, int offset, int maxlen, shairport_lcm_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __shairport_lcm_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __shairport_lcm_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int shairport_lcm_t_decode_cleanup(shairport_lcm_t *p)
{
    return __shairport_lcm_t_decode_array_cleanup(p, 1);
}

int __shairport_lcm_t_clone_array(const shairport_lcm_t *p, shairport_lcm_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __string_clone_array(&(p[element].message), &(q[element].message), 1);

        __int32_t_clone_array(&(p[element].value), &(q[element].value), 1);

    }
    return 0;
}

shairport_lcm_t *shairport_lcm_t_copy(const shairport_lcm_t *p)
{
    shairport_lcm_t *q = (shairport_lcm_t*) malloc(sizeof(shairport_lcm_t));
    __shairport_lcm_t_clone_array(p, q, 1);
    return q;
}

void shairport_lcm_t_destroy(shairport_lcm_t *p)
{
    __shairport_lcm_t_decode_array_cleanup(p, 1);
    free(p);
}

int shairport_lcm_t_publish(lcm_t *lc, const char *channel, const shairport_lcm_t *p)
{
      int max_data_size = shairport_lcm_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = shairport_lcm_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _shairport_lcm_t_subscription_t {
    shairport_lcm_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void shairport_lcm_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    shairport_lcm_t p;
    memset(&p, 0, sizeof(shairport_lcm_t));
    status = shairport_lcm_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding shairport_lcm_t!!!\n", status);
        return;
    }

    shairport_lcm_t_subscription_t *h = (shairport_lcm_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    shairport_lcm_t_decode_cleanup (&p);
}

shairport_lcm_t_subscription_t* shairport_lcm_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    shairport_lcm_t_handler_t f, void *userdata)
{
    shairport_lcm_t_subscription_t *n = (shairport_lcm_t_subscription_t*)
                       malloc(sizeof(shairport_lcm_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 shairport_lcm_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg shairport_lcm_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int shairport_lcm_t_subscription_set_queue_capacity (shairport_lcm_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int shairport_lcm_t_unsubscribe(lcm_t *lcm, shairport_lcm_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe shairport_lcm_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

