"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class shairport_lcm_t(object):
    __slots__ = ["message", "value"]

    def __init__(self):
        self.message = ""
        self.value = 0

    def encode(self):
        buf = BytesIO()
        buf.write(shairport_lcm_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __message_encoded = self.message.encode('utf-8')
        buf.write(struct.pack('>I', len(__message_encoded)+1))
        buf.write(__message_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">i", self.value))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != shairport_lcm_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return shairport_lcm_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = shairport_lcm_t()
        __message_len = struct.unpack('>I', buf.read(4))[0]
        self.message = buf.read(__message_len)[:-1].decode('utf-8', 'replace')
        self.value = struct.unpack(">i", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if shairport_lcm_t in parents: return 0
        tmphash = (0xbcf266f30c19dbf7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if shairport_lcm_t._packed_fingerprint is None:
            shairport_lcm_t._packed_fingerprint = struct.pack(">Q", shairport_lcm_t._get_hash_recursive([]))
        return shairport_lcm_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

